import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useSettings } from "@/context/SettingsContext";
import type { TranslationKey } from "@/i18n/translations";

type StatusType = "active" | "inactive" | "occupied" | "vacant" | "reserved" | "unavailable" | "archived" | "draft" | "pending-signature" | "signed" | "ended" | "terminated" | "former" | "applicant" | "due" | "paid" | "partially-paid" | "overdue" | "pending" | "incomplete" | "released" | "partially-retained" | "under-notice" | "overdue-end" | "in-review" | "completed" | "scheduled" | "not-scheduled" | "open" | "assigned" | "in-progress" | "cancelled" | "low" | "medium" | "high" | "urgent" | "none" | "fully-consumed" | "disputed" | "written-off" | "imported" | "unmatched" | "partially-matched" | "matched" | "exception" | "reversed" | "refunded" | "owner-only" | "tenant-recoverable" | "partially-recoverable" | "informational" | "move-in-pending" | "move-out-scheduled" | "available-soon" | "not-applicable";

const statusStyles: Record<StatusType, string> = {
  active: "bg-success/15 text-success border-success/30",
  occupied: "bg-success/15 text-success border-success/30",
  vacant: "bg-warning/15 text-warning border-warning/30",
  reserved: "bg-primary/15 text-primary border-primary/30",
  unavailable: "bg-muted text-muted-foreground border-border",
  archived: "bg-muted/60 text-muted-foreground border-dashed border-border italic",
  inactive: "bg-muted text-muted-foreground border-border",
  draft: "bg-muted text-muted-foreground border-border",
  "pending-signature": "bg-warning/15 text-warning border-warning/30",
  signed: "bg-primary/15 text-primary border-primary/30",
  ended: "bg-neutral text-neutral-foreground border-neutral-foreground/30",
  terminated: "bg-destructive/15 text-destructive border-destructive/30",
  former: "bg-muted text-muted-foreground border-border",
  applicant: "bg-primary/15 text-primary border-primary/30",
  due: "bg-primary/15 text-primary border-primary/30",
  paid: "bg-success/15 text-success border-success/30",
  "partially-paid": "bg-warning/15 text-warning border-warning/30",
  overdue: "bg-destructive/15 text-destructive border-destructive/30",
  pending: "bg-warning/15 text-warning border-warning/30",
  incomplete: "bg-warning/15 text-warning border-warning/30",
  released: "bg-muted text-muted-foreground border-border",
  "partially-retained": "bg-destructive/15 text-destructive border-destructive/30",
  "under-notice": "bg-warning/15 text-warning border-warning/30",
  "overdue-end": "bg-destructive/20 text-destructive border-destructive/40 font-semibold",
  "in-review": "bg-warning/15 text-warning border-warning/30",
  completed: "bg-success/15 text-success border-success/30",
  scheduled: "bg-primary/15 text-primary border-primary/30",
  "not-scheduled": "bg-muted text-muted-foreground border-border",
  open: "bg-warning/15 text-warning border-warning/30",
  assigned: "bg-primary/15 text-primary border-primary/30",
  "in-progress": "bg-warning/15 text-warning border-warning/30",
  cancelled: "bg-muted text-muted-foreground border-border",
  low: "bg-muted text-muted-foreground border-border",
  medium: "bg-primary/15 text-primary border-primary/30",
  high: "bg-warning/15 text-warning border-warning/30",
  urgent: "bg-destructive/15 text-destructive border-destructive/30",
  "fully-consumed": "bg-success/15 text-success border-success/30",
  none: "bg-muted text-muted-foreground border-border",
  disputed: "bg-destructive/15 text-destructive border-destructive/30",
  "written-off": "bg-muted text-muted-foreground border-border",
  imported: "bg-primary/15 text-primary border-primary/30",
  unmatched: "bg-warning/15 text-warning border-warning/30",
  "partially-matched": "bg-warning/15 text-warning border-warning/30",
  matched: "bg-success/15 text-success border-success/30",
  exception: "bg-destructive/15 text-destructive border-destructive/30",
  reversed: "bg-muted text-muted-foreground border-border",
  refunded: "bg-muted text-muted-foreground border-border",
  "owner-only": "bg-destructive/15 text-destructive border-destructive/30",
  "tenant-recoverable": "bg-success/15 text-success border-success/30",
  "partially-recoverable": "bg-warning/15 text-warning border-warning/30",
  informational: "bg-muted text-muted-foreground border-border",
  "move-in-pending": "bg-primary/15 text-primary border-primary/30",
  "move-out-scheduled": "bg-warning/15 text-warning border-warning/30",
  "available-soon": "bg-success/15 text-success border-success/30",
  "not-applicable": "bg-muted text-muted-foreground border-border",
};

const STATUS_KEYS: Record<StatusType, TranslationKey> = {
  active: "status.active",
  inactive: "status.inactive",
  occupied: "status.occupied",
  vacant: "status.vacant",
  reserved: "status.reserved",
  unavailable: "status.unavailable",
  archived: "status.archived",
  draft: "status.draft",
  "pending-signature": "status.pendingSignature",
  signed: "status.signed",
  ended: "status.ended",
  terminated: "status.terminated",
  former: "status.former",
  applicant: "status.applicant",
  due: "status.due",
  paid: "status.paid",
  "partially-paid": "status.partiallyPaid",
  overdue: "status.overdue",
  pending: "status.pending",
  incomplete: "status.incomplete",
  released: "status.released",
  "partially-retained": "status.partiallyRetained",
  "under-notice": "status.underNotice",
  "overdue-end": "status.overdueEnd",
  "in-review": "status.inReview",
  completed: "status.completed",
  scheduled: "status.scheduled",
  "not-scheduled": "status.notScheduled",
  open: "status.open",
  assigned: "status.assigned",
  "in-progress": "status.inProgress",
  cancelled: "status.cancelled",
  low: "status.low",
  medium: "status.medium",
  high: "status.high",
  urgent: "status.urgent",
  "fully-consumed": "status.fullyConsumed",
  none: "status.none",
  disputed: "status.disputed",
  "written-off": "status.writtenOff",
  imported: "status.imported",
  unmatched: "status.unmatched",
  "partially-matched": "status.partiallyMatched",
  matched: "status.matched",
  exception: "status.exception",
  reversed: "status.reversed",
  refunded: "status.refunded",
  "owner-only": "status.ownerOnly",
  "tenant-recoverable": "status.tenantRecoverable",
  "partially-recoverable": "status.partiallyRecoverable",
  informational: "status.informational",
  "move-in-pending": "status.moveInPending",
  "move-out-scheduled": "status.moveOutScheduled",
  "available-soon": "status.availableSoon",
  "not-applicable": "status.none",
};

export function StatusBadge({ status }: { status: StatusType }) {
  const { t } = useSettings();
  return (
    <Badge variant="outline" className={cn("font-medium text-xs", statusStyles[status])}>
      {t(STATUS_KEYS[status])}
    </Badge>
  );
}
